### ISSUE TITLE
사이트가 정상출력이 되지 않네요. 

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#1]
혹시 설치경로가 /XE라서 그런지요 ??

![default](https://cloud.githubusercontent.com/assets/6590236/7665364/a30dc626-fbee-11e4-9f7e-d28fbc58af81.png)

**Comment by wookho** [comment]
서브페이지만 선택적으로 사용을하면 사이트가 서브쪽은 정상으로 출력됩니다.

**Comment by wookho** [comment]
서브페이지만 따로 사용을 해봐도 동일하게 깨지는군요.

**Comment by kijin** [comment]
실제로 소스가 어떻게 나오고 있는지 확인할 수 없으니 답답하네요.

정상 작동할 경우 CSS 참조 갯수가 확 줄어들고, `/xe/files/cache/zipperupper/`로 시작되는 주소의 CSS 파일 하나에 모두 들어가야 합니다. 혹시 이것이 존재하지 않는다면 퍼미션 문제나 그 밖의 오류 때문에 캐시파일 생성에 실패한 거고요.

**Comment by wookho** [comment]
@kijin 접속이 적을 것 같은 게시판 한개 적용해 놓았습니다.

http://pomelove.com/xe/news

**Comment by wookho** [comment]
@kijin 해당폴더와 파일이 생성이 되지 않고 있는데요. 어떤폴더의 퍼미션을 어떻게 조정해야 할까요 ?

**Comment by wookho** [comment]
@kijin /xe/files/cache  의 cache 폴더의 권한은 755 로 되어 있습니다.

**Comment by kijin** [comment]
`cache` 폴더 내에 `zipperupper`라는 폴더를 직접 생성한 후에 퍼미션 777로 해보세요.

**Comment by wookho** [comment]
@kijin 말씀하신대로 수동으로 폴더직접 생성하고 퍼미션 777로 해주소 정상출력되네요.

**Comment by kijin** [comment]
잘 된다니 다행이네요 ^^

파일 생성에 실패할 경우 에러메시지를 띄우거나 기존의 CSS 링크들을 원래대로 돌려놓는 기능을 만들어야겠네요. 아직 안정화되지 않은 애드온을 실험해 주셔서 감사합니다.

**Comment by wookho** [comment]
@kijin 문제가 하나 발견되었는데요. 메인페이지의 폰트어썸이 표시되지 않네요. 폰트어썸애드온을 사용하고 있습니다.

**Comment by kijin** [comment]
폰트 파일 위치가 원본파일의 상대경로로 지정되어 있는데, 이걸 합쳐진 파일 기준의 상대경로로 변환하는 과정에서 문제가 생기는 것 같네요. 고쳐서 다시 커밋하겠습니다.

**Comment by wookho** [comment]
요건 Close 하고 새로 등록할게요.
