### ISSUE TITLE
XE 관리자 기능에서 문제가 있네요.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#10]
공홈자료실의 의견 보고 확인해 보았더니 관리자가 분류를 추가하거나 혹은 위젯크기,위젯스타일등을 수정하거나 할때 디자인이 깨져서 사용하지 못하는 부분이 있네요. 

물론 애드온을 해제하고 작업하는 방법이 있습니다.

**Comment by kijin** [comment]
일부 파일에 UTF-8 BOM(`"\xEF\xBB\xBF"`)이 포함되어 있어서 합칠 때 오류가 발생하는 것 같습니다. BOM을 제외하고 합치도록 조치했으니, 방금 커밋한 것으로 테스트 부탁드립니다.

**Comment by wookho** [comment]
감사합니다. 위젯크기,스타일,분류추가 등 모두 문제없네요.
