### ISSUE TITLE
이런 문제가 있다는데 한 번 확인해보세요 ㅎ

### ISSUE THREAD

**Issue by eondcom** [kijin/xe-zipperupper#15]
https://www.xpressengine.com/qna/23003915

**Comment by kijin** [comment]
CSS를 하나로 합칠 경우 문제가 생기는 레이아웃은 어쩔 수 없습니다. 특히 모바일쪽은 media 쿼리를 많이 사용하기 때문에 합치기 곤란한 경우가 많더군요.

불필요하게 적용해서 문제를 일으키는 일이 너무 많은 것 같아서, CSS 갯수 제한이 있는 구버전 IE 외에는 아예 작동하지 않도록 해버리는 것도 고려하고 있습니다 ㅠㅠ
