### ISSUE TITLE
메인페이지에서 폰트어썸이 출력되지 않습니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#2]
폰트어썸애드온을 이용하여 폰트어썸을 출력하고있으나 메인페이지에서 출력되지 않네요.

**Comment by kijin** [comment]
CSS 파일 내의 상대경로를 변환할 때 `?v=4.2.0`과 같은 쿼리스트링이 붙어 있으면 정상적으로 변환되지 않는 문제가 있었습니다. 방금 커밋한 버전으로 다시 시도해 보세요.

**Comment by wookho** [comment]
@kijin 새파일로 교체하고 캐시파일재생성까지 하니 정상으로 출력됩니다. 감사합니다.

**Comment by kijin** [comment]
캐시파일도 자동으로 재생성되도록 해봐야겠네요. 혹시 또 문제가 있으면 언제든지 이슈 열어 주세요.
