### ISSUE TITLE
최종버전 적용 후 애드온이 기능이 유효하지 않네요.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#3]
메인페이지 폰트어썸이 잘 나와 그것만 해결이 된 것으로 파악했는데 그것이 아니고 애드온 기능이 적용되지 않아 원래의 CSS를 각기 다 불러 오고 있습니다.

**Comment by kijin** [comment]
캐시를 지우시면서 퍼미션 문제가 다시 생겼나 봅니다. 새 버전에서는 합친 파일 생성에 실패할 경우 원래 CSS를 복구하도록 했거든요.

**Comment by wookho** [comment]
@kijin 그러네요. 폴더가 사라지고 없네요. 다시 폴더를 만들어보겠습니다.

**Comment by wookho** [comment]
@kijin 폴더를 수동을 만들어주고 퍼미션을 주고 하면 정상으로 돌아옵니다만....  문제는 캐시가 재생성되고 나면 다시 폴더가 사라져버려서 기능을 다시 상실하네요.

**Comment by kijin** [comment]
전반적인 퍼미션을 한번 점검해 보셔야겠습니다. `files` 폴더 내에는 XE 코어, 모듈, 애드온들이 자유롭게 파일과 폴더를 생성할 수 있어야 하거든요. 이런 문제는 대개 FTP 계정 소유의 파일과 웹서버 계정 (`www-data`) 소유의 파일이 뒤섞여 있어서 발생합니다.

**Comment by wookho** [comment]
@kijin 다른 자료의 경우 사용에 문제가 아직까지 한번도 없었는데요... 흠...  그리고 한가지 특이사항이 더 있습니다. IE8에서는 지금 메인페이지에서 폰트어썸이 출력되지 않네요.

**Comment by kijin** [comment]
방금 커밋한 버전으로 다시 시도를 부탁드립니다.

**Comment by wookho** [comment]
@kijin 앗.. 2가지 문제 모두 해결되었습니다. 캐시재생성해도 문제없구요. IE8에서도 폰트어썸 출력 잘됩니다.

그런데 제가 files 폴더이하 모두를 777로 변경해 놓았는데 이건 앞으로 XE 사용에 문제는 되지 않겠죠 ?

**Comment by wookho** [comment]
@kijin config 폴더만 755로 바꿔 놓으면 될까요 ???

**Comment by kijin** [comment]
퍼미션은 그냥 원래대로 해 두세요. 제 애드온 쪽에서 고쳤습니다.

추가로 문제가 없다면 오늘은 이 정도 하고, 내일 전체적으로 다시 한 번 점검해 볼게요. 급조한 애드온 공개 첫날 마루타 노릇 하시느라 수고하셨습니다 ^____^

**Comment by wookho** [comment]
퍼미션을 일괄 다 적용해버려서 맞는게 뭔지 모르겠네요. 말씀하신대로 퍼미션과 상관없이 애드온 수정으로 조치가 된 것은 확인했어요.

**Comment by kijin** [comment]
그냥 둬도 됩니다. 우분투 서버를 단독으로 운영하시는 것 같은데, 이 경우 퍼미션 777로 내버려둬도 보안상 별 문제 없어요. 777이 위험한 경우는 웹호스팅처럼 전혀 모르는 사람들이 서버를 공유하는 경우죠.

파일 소유자가 웹서버 계정(`www-data`)과 같다면 755로 다시 돌려놓아도 무방합니다.
