### ISSUE TITLE
관리자페이지 데시보드 순방문자 순페이지뷰 안보임

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#4]
이슈 하나만 더 열고 갈게요 ㅋ 
사이트 이용에는 큰 문제가 아니니 뭐 다음 업데이트때 함께 하셔서 등록하셔도 될 것 같습니다.

제목대로 관리자페이지에서 방문자와 페이지뷰가 보이지 않는 현상이 있네요.

**Comment by kijin** [comment]
Fixed in d52face
