### ISSUE TITLE
모바일에서 글 작성 댓글 작성이 안됩니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#5]
모바일에서 글 작성 댓글작성 등록버튼을 눌러도 동작하지 않는 문제가 있네요.
현재는 모바일 비활성화 상태입니다.

**Comment by wookho** [comment]
어....  최신커밋으로 적용하니 모바일 작성이 되네요.

**Comment by kijin** [comment]
`<!--[if lt IE 9]>` 이런 식으로 구버전 IE에서만 로딩되어야 하는 스크립트가 브라우저를 가리지 않고 무조건 합쳐져 버리는 문제가 있었습니다. 아마 이것 때문에 IE가 아닌 브라우저에서 오류가 났을 것으로 생각되네요. `targetie` 속성을 가진 스크립트는 실제 구버전 IE에서만 작동하도록 고쳤습니다.
