### ISSUE TITLE
XEicon 에러가 나네요.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#6]
http://pomelove.com/xe/weather

페이지를 보시면 에러가 발생합니다.

**Comment by kijin** [comment]
XEicon뿐만 아니라 폰트어썸과 그 밖의 `url()`이 다 깨졌네요 ㅠ

방금 커밋한 35a2d1c 이걸로 시도해 보시겠어요?

**Comment by wookho** [comment]
감사합니다. 잘 되네요. 그런데 저희는 일부 css도 불러오는데 정상동작하는거는 맞겠지요 ?
물론 IE8에서 에디터도 잘 열리곤 합니다.

link rel="stylesheet" href="/xe/common/css/xe.css?20150409102120" />
//<link rel="stylesheet" href="/xe/files/cache/zipperupper/2fea25aaf259eec0e62ddc8b66d8aa8d6ed2e66f.css?20150517193010" />
link rel="stylesheet" href="/xe/widgets/plusadWidget/skins/default/css/default.css?20140419125448" />
link rel="stylesheet" href="/xe/widgets/counter_status/skins/webmini_counter/css/widget.css?20130409161959" />
link rel="stylesheet" href="/xe/widgets/newest_document/skins/wm_dm_none/css/white.css?20120928112044" />
link rel="stylesheet" href="/xe/widgets/newest_comment/skins/wm_cm_none/css/white.css?20120928112043" />
link rel="stylesheet" href="/xe/widgets/contentextended/skins/default/css/widget.css?20141110165910" />
link rel="stylesheet" href="/xe/widgets/popular_document/skins/jdh_default/normal/style.css?20150423171015" />
link rel="stylesheet" href="/xe/widgets/content/skins/default/css/widget.css?20150219141233" />

**Comment by kijin** [comment]
역시 상대경로 변환 부분이 말썽이었군요. 최대한 다양한 사용환경을 고려한다고 해도, 서버 설정 어딘가에 슬래시(`/`)가 하나 더 들어가고 덜 들어가고에 여전히 너무 영향을 받네요 ㅠㅠ

#5 에서 말씀드린 것처럼, 합쳐버렸을 때 문제가 발생할 가능성이 조금이라도 있어 보이는 파일은 합치지 않고 그냥 두도록 변경했습니다. 그래서 zipperupper를 사용하더라도 합쳐지지 않는 CSS 파일이 있을 수도 있어요. 애드온 처리가 모두 끝난 다음에 실행되는 위젯 역시 어쩔 수 없고요. (실행 순서는 제멋대로 바뀌기도 하더군요. 애드온을 한두번 껐다 켰다 하면 순서가 또 바뀔 수도 있습니다.)

기능에 영향을 주지 않는 범위 내에서 최대한 많은 CSS를 합칠 수 있도록 계속 여러가지 방법을 찾고 있지만, 뭐 하나 또 잘못 건드려서 이상하게 될까봐 조심스럽네요 ㅎㅎ

**Comment by wookho** [comment]
네. 잘알겠습니다. 애드온사용으로 인한 효과의 차이이니 문제는 아니겠네요. 감사합니다.
