### ISSUE TITLE
이 자료 설치 이후 로그인이 풀립니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#7]
잠시 사이트 이용을 하지 않은 후 다시 와보면 로그인이 풀려있네요. 자료설치 이전까지는 로그인 풀림이 없었던 사이트라 이 자료에서 확인이 필요할 듯합니다.
검토 부탁드릴게요.

**Comment by kijin** [comment]
음, 세션은 전혀 건드리지 않는데 왜 그럴까요?

님의 사이트를 보니 웹소켓을 사용하는 기능이 있는 것 같은데, 혹시 이게 정상적으로 작동하고 있는지 확인해 주실 수 있을까요? 일정한 간격으로 서버에 요청을 보내면서 세션을 유지하고 있었는데 이게 고장나는 바람에 세션이 유지되지 않는 것인지도 모르겠습니다.

IE에서 문제가 되는 부분은 JS가 아니라 CSS뿐이기 때문에, 정 불편하시면 JS는 모으지 않고 CSS만 모으도록 설정할 수도 있습니다. `zipperupper.addon.php` 맨 마지막 줄의 `$zipperupper->zipUp();` 이 코드를 `$zipperupper->zipCSS();` 이렇게 바꾸시면 됩니다. 이렇게 설정해도 같은 문제가 발생하는지 알려주시면 감사하겠습니다.

**Comment by wookho** [comment]
@kijin 네. 웹소켓은 실시간글알림2 애드온때문에 사용하고 있습니다. 실시간알림2 애드온 재사용시점(웹소켓)이 이 자료 설치 시기와 비슷하긴 합니다. 왜냐면 아약스보드의 html5알림플러그인이 IE에서 CK에디터를 비활성화 시켜서 인데요.

실시간 알림2애드온 및 node.js는 정상동작은 하고 있습니다.

현재 로그인이 풀리는 것이 확인된 곳은 크롬에서 확인했습니다.

**Comment by wookho** [comment]
그리고 방금 확인한 사항인데요. 저희 사이트는 말씀하신 것 적용하기 전부터 js는 모으지 않고 있었네요.

**Comment by wookho** [comment]
@kijin 아.. 아닙니다. js도 모아주고 있군요. 정정합니다. 다시 적용해 보고 알려드리겠습니다.

**Comment by wookho** [comment]
@kijin 지금 사이트를 재방문해 보니 로그인이 풀려 있지는 않네요.

**Comment by wookho** [comment]
$zipperupper->zipCSS();  로 수정 후 대기 시간이 좀 짧은거 같아 로그아웃이 되는 시간인 2시간 이상으로 다시 모니터링 해보겠습니다.

 $zipperupper->zipUp();  상태에서는 2시간 이내에 로그아웃 되는 것 같습니다.

**Comment by kijin** [comment]
네, 충분한 시간을 가지고 테스트해 보세요. XE의 로그인 관련 버그는 디버깅하기가 상당히 까다롭습니다. 저번에 세션쉴드 애드온을 만들었을 때도 로그인풀림 때문에 삽질했죠 ㅠ

근데 `php.ini`의 `session.gc-maxlifetime` 설정은 어떻게 되어 있나요? 일반적인 기본값이 1440초(24분)밖에 되지 않아서 멀쩡한 세션도 날아가버리는 문제가 종종 있습니다.

**Comment by wookho** [comment]
@kijin 역시 풀리는군요. 제가 뭔가 착각을 했거나 그랬을 수 있겠습니다. 다시 확인이 되면 열도록 할게요.
