### ISSUE TITLE
시험모듈에서 XEicon 이 나오지 않는데요.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-zipperupper#9]
http://pomelove.com/xe/test

저희 사이트 시험모듈입니다. 요기도 XEicon이 나왔으면 좋겠습니다.

**Comment by kijin** [comment]
다른 모듈에서는 XEIcon이 정상적으로 나오는데 시험모듈에서만 안 나온다면 시험모듈 쪽 문제가 아닐까요? CSS를 확인해 보니 XE에 기본 포함된 XEIcon 폰트를 사용하지 않고 시험모듈 스킨에 포함된 폰트를 로딩하고 있네요. 경로는 정상적으로 변환되는 것을 확인했습니다.

**Comment by wookho** [comment]
@kijin 네. 그럼 공통으로 쓰는쪽으로 경로를 시험모듈에서 수정해 볼게요.

**Comment by wookho** [comment]
@kijin  경로를 바꾸고 싶은데 잘 안되네요. 일단 모듈에서 별도로 사용하는 경로를 사용해도 정상적으로 보여야 할 것 같습니다. 다른자료(예방접종다이어리:스케츌모듈)의 경우도 별도로 해당자료에서 xeicon폴더를 제공하고 해당 경로에서 불러오는방식인데 잘 나오거든요...

일단 현재 이 페이지만 애드온적용에서 제외하였으니 한번 살펴봐주세요.

**Comment by kijin** [comment]
다른 모듈은 [여기 보다시피](http://pomelove.com/xe/modules/myschedule/skins/default/xeicon/xeicon.css) 폰트 파일에 링크만 하고 있는데, 시험모듈은 [이렇게](http://pomelove.com/xe/modules/exam/skins/default/css/xeicon.css) 폰트파일을 통째로 CSS에 쑤셔넣어 놓았어요. 아마 이것 때문에 차이가 생기는 게 아닌가 싶습니다.

애드온 켠 상태와 끈 상태를 비교해야 하니, 해당페이지에도 애드온을 다시 적용해 보세요.

**Comment by wookho** [comment]
@kijin 네. 다시 모듈에서 애드온사용하게 해 놓았구요. 만약 모듈에서의 잘못된 사용으로 모듈에서 많은 수정을 해야 한다면 그냥 해당 모듈은 애드온 사용안하는 것으로 하겠습니다.

**Comment by kijin** [comment]
제 버그가 맞네요. 최신커밋으로 다시 시도 부탁드립니다.

**Comment by wookho** [comment]
@kijin 네. 감사합니다. 정상출력되네요.
